# Generated by Django 4.2.5 on 2023-12-20 09:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('1', 'HOD'), ('2', 'Admin'), ('3', 'Employee'), ('4', 'Agent'), ('5', 'Out Sourcing Agent'), ('6', 'Customer')], default='1', max_length=10)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=20)),
                ('branch_source', models.CharField(choices=[('COCO', 'Company Owned Company Operated'), ('COFO', 'Company Owned Franchise Operated'), ('FOCO', 'Franchise Owned Company Operated'), ('FOFO', 'Franchise Owned Franchise Operated')], max_length=50)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.IntegerField()),
                ('docker_no', models.CharField(max_length=100)),
                ('sender_no', models.CharField(blank=True, max_length=15, null=True)),
                ('receiver_no', models.CharField(blank=True, max_length=15, null=True)),
                ('courier_no', models.CharField(blank=True, max_length=15, null=True)),
                ('receiver_address', models.CharField(max_length=150)),
                ('sender_address', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('Pick', 'Pick'), ('In Transit', 'In Transit'), ('Receive', 'Receive')], max_length=50)),
                ('lastupdated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document_category', models.CharField(max_length=200)),
                ('lastupdated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('Presales/Assesment', 'Presales/Assesment'), ('Sales', 'Sales'), ('Documentation', 'Documentation'), ('Visa Team', 'Visa Team'), ('HR', 'HR')], max_length=20, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/Employee/profile_pic/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='VisaCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('lastupdated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('visa_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.visacountry')),
            ],
            options={
                'db_table': 'VisaCategory',
            },
        ),
        migrations.CreateModel(
            name='OutSourcingAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('zipcode', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InReview', 'InReview'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Pending', max_length=255)),
                ('activeinactive', models.BooleanField(blank=True, default=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/OutSourcing/Agent/Profile Pic/')),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('registeron', models.DateTimeField(auto_now_add=True)),
                ('adhar_card_front', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('adhar_card_back', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('pancard', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('assign_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.employee')),
                ('registerdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_outsourcingagents', to=settings.AUTH_USER_MODEL)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='Web', max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('login_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group_member', models.ManyToManyField(related_name='groups_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('document_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.documentcategory')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseCategoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_category', to='crm_app.visacategory')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm_app.visacountry')),
                ('document', models.ManyToManyField(related_name='document', to='crm_app.document')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('zipcode', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InReview', 'InReview'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Pending', max_length=255)),
                ('activeinactive', models.BooleanField(blank=True, default=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/Agent/Profile Pic/')),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('registeron', models.DateTimeField(auto_now_add=True)),
                ('adhar_card_front', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('adhar_card_back', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('pancard', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc')),
                ('assign_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.employee')),
                ('registerdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_agents', to=settings.AUTH_USER_MODEL)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=10, unique=True)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
