# Generated by Django 4.2.5 on 2023-12-21 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('number_of_visa', models.IntegerField()),
                ('amount', models.CharField(max_length=100)),
                ('advance_amount', models.CharField(max_length=100)),
                ('file_charges', models.CharField(max_length=100)),
                ('package_expiry_date', models.DateField(blank=True, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/package_images/')),
                ('assign_to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.group')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visa_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_category', to='crm_app.visacategory')),
                ('visa_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.visacountry')),
                ('visa_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_subcategory', to='crm_app.visacategory')),
            ],
        ),
    ]
