# Generated by Django 4.2.5 on 2023-12-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='visa_subcategory',
        ),
    ]
