# Generated by Django 4.2.5 on 2023-12-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_employee_tata_tele_agent_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='tata_tele_agent_name',
            new_name='tata_tele_agent_number',
        ),
    ]
