# Generated by Django 4.2.5 on 2023-12-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_rename_tata_tele_agent_name_employee_tata_tele_agent_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50, null=True),
        ),
    ]
