# Generated by Django 4.2.5 on 2023-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_alter_agent_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
