# Generated by Django 4.2.5 on 2023-12-22 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_visasubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('departure_city', models.CharField(max_length=100)),
                ('number_of_people', models.PositiveIntegerField()),
                ('departure_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FrontWebsiteEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Appointment', 'Appointment'), ('Contact Us', 'Contact Us')], default='Appointment', max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/frontwebsiteenquiry/')),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.visacategory')),
                ('country_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.visacountry')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
