# Generated by Django 4.2.5 on 2023-12-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_booking_frontwebsiteenquiry'),
        ('crm_app', '0006_agentagreement'),
    ]

    operations = [
    ]
