# Generated by Django 4.2.5 on 2023-12-22 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_merge_20231222_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salutation', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Master', 'Master')], max_length=20, null=True)),
                ('FirstName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('MiddleName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=100, null=True)),
                ('Visa_type', models.CharField(blank=True, choices=[('Single', 'Single'), ('Couple', 'Couple'), ('Family', 'Family')], max_length=50, null=True)),
                ('Source', models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Reference', 'Reference'), ('Youtube', 'Youtube'), ('WhatsApp', 'WhatsApp'), ('Google', 'Google'), ('Others', 'Others')], max_length=100, null=True)),
                ('Reference', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_status', models.CharField(choices=[('New Lead', 'New Lead'), ('Accept', 'Accept'), ('Active', 'Active'), ('PreEnrolled', 'PreEnrolled'), ('Enrolled', 'Enrolled'), ('Inprocess', 'Inprocess'), ('Ready To Submit', 'Ready To Submit'), ('Appointment', 'Appointment'), ('Ready To Collection', 'Ready To Collection'), ('Result', 'Result'), ('Delivery', 'Delivery'), ('Pending', 'Pending'), ('Reject', 'Reject'), ('Archive', 'Archive'), ('Case Initiated', 'Case Initiated')], default='New Lead', max_length=100)),
                ('enquiry_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('digital_signature', models.FileField(blank=True, null=True, upload_to='media/Digital Signature/')),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('spouse_no', models.CharField(blank=True, max_length=15, null=True)),
                ('spouse_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('spouse_passport', models.CharField(blank=True, max_length=50, null=True)),
                ('spouse_dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('mailing_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('mailing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('permanent_country', models.CharField(blank=True, max_length=244, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('passport_no', models.CharField(max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expirty_Date', models.DateField(blank=True, null=True)),
                ('issue_country', models.CharField(blank=True, max_length=255, null=True)),
                ('city_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_birth', models.CharField(blank=True, max_length=244, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('more_than_country', models.BooleanField(blank=True, null=True)),
                ('other_country', models.BooleanField(blank=True, null=True)),
                ('more_than_one_country', models.CharField(blank=True, max_length=100, null=True)),
                ('studyin_in_other_country', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relation_With_applicant', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('case_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('archive', models.BooleanField(blank=True, default=False, null=True)),
                ('Package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.package')),
                ('Visa_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_category', to='crm_app.visacategory')),
                ('Visa_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.visacountry')),
                ('Visa_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_subcategory', to='crm_app.visacategory')),
                ('assign_to_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.agent')),
                ('assign_to_documentation_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_emp', to='crm_app.employee')),
                ('assign_to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.employee')),
                ('assign_to_outsourcingagent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.outsourcingagent')),
                ('assign_to_sales_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_emp', to='crm_app.employee')),
                ('assign_to_visa_team_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_team_emp', to='crm_app.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Enquiry',
            },
        ),
    ]
